### ISSUE TITLE
Something wrong when i set num_query_val to 1.

### ISSUE THREAD

**Issue by P-DX** [orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch#16]
Hello, thank you for the code provided.
When I set num_query_val to 1, why val_acc and test_acc will not change, and it is always about num_query_val / classes_per_it_val, can you tell me what went wrong? 
Thank you! Looking forward to your reply.

**Comment by d-li14** [comment]
Because function `torch.eq` [here](https://github.com/orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch/blob/master/src/prototypical_loss.py#L84) yields a 5x5 identity matrix.
