### ISSUE TITLE
Testing Error

### ISSUE THREAD

**Issue by ralphatobe** [orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch#18]
When testing, the network calculates loss using the number of supports specified for the training regime. This appears to be an error, but perhaps I've missed something?

`_, acc = loss_fn(model_output, target=y, n_support=opt.num_support_tr)`

To me, this line should be

`_, acc = loss_fn(model_output, target=y, n_support=opt.num_support_val)`

**Comment by dnlcrl** [comment]
fixed in 5e18a5e5b369903092f683d434efb12c7c40a83c, thank you!
