### ISSUE TITLE
About Miniimagenet

### ISSUE THREAD

**Issue by Dylanbron** [orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch#22]
Do you mind share your code about miniimagenet dataloader and train? It will be appreciated.

**Comment by dnlcrl** [comment]
Hi @ Dylanbron, unfortunately we haven't trained the model on the MiniImageet dataset, you might want to check the repository from the paper's authors for that: 
https://github.com/jakesnell/prototypical-networks
