### ISSUE TITLE
dimension error

### ISSUE THREAD

**Issue by annkennedy** [orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch#6]
Running `python train.py --cuda -nsTr 1 -nsVa 1` gives me a runtime error in euclidean_dist ("dimension out of range (expected to be in range of [-1, 0], but got 1)")

It seems the code is trying to compute a distance between `query_samples` (a matrix size 360x64) and `prototypes` (a *vector* length 60)- so yeah, I can see why it's producing this error. But why are `query_samples` and `prototypes` these sizes, to begin with? Shouldn't they have the same value in size(1)?

**Comment by annkennedy** [comment]
Aha- in prototypical_loss.py line 72, you need to get rid of the `mean(0)` in the case where the support = 1 (since the first dimension of `input_cpu` in this case is the image dimension, not the support size). So a full correction would be to replace line 72 with:
```
if support_idxs[0].size(0)>1:
    prototypes = torch.stack([input_cpu[i].mean(0) for i in support_idxs])
else:
    prototypes = torch.stack([input_cpu[i] for i in support_idxs])
```

**Comment by Fangwq** [comment]
I'm sorry and it is still wrong. Now I got: RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by haofusheng** [comment]
you can try this:

if support_idxs[0].size() != ():
    prototypes = torch.stack([input_cpu[i].mean(0) for i in support_idxs])
else:
    prototypes = torch.stack([input_cpu[i] for i in support_idxs])

it works for me

**Comment by dnlcrl** [comment]
Hello, I'm investigating this issue right now and trying to figure out what is happening and how to handle it. Thank you

**Comment by dnlcrl** [comment]
as I thought the solution was simple as adding one parameter to a torch function call :) 
here: https://github.com/orobix/Prototypical-Networks-for-Few-shot-Learning-PyTorch/blob/8492a4441fa1f88466a590cc84fa4d420d0bf0a5/src/prototypical_loss.py#L61

When calling squeeze without arguments on a multidimensional tensor having only one element, it will return a scalar value (not a tensor), while in the case of `n_support`=1 we still want to return a torch tensor (with one element in it). So now we specify the squeeze dimension and `support_idxs` will still be a list of torch tensors (as in the case of `n_support` > 1) and no more a list of torch scalars, which was causing the error. 

Thank you for contributing! You can try to pull and re-run your experiments now, let me know if you find other issues!

**Comment by Fangwq** [comment]
That works, thank you very much! @haofusheng
